### ISSUE TITLE
Fetching events from Notion database

### ISSUE THREAD

**Issue by rafaelcestti** [INIT-Build-Web-Dev-3-Spring-2024/init-website#5]
Working on fetching events from the Notion database, mainly today's events & this week's events.

**Comment by pm-fer** [comment]
Working on the event card component that shows the events from Notion. I'm migrating it from the old website, so we'd be missing a picture, program name and description.

**Comment by pm-fer** [comment]
Event component is working with static information for now. It should be able to populate based on Notion API's data but it's still missing picture, program name, event scription and Luma link.
